### ISSUE TITLE
Issue when call send_message function

### ISSUE THREAD

**Issue by datnguyen0606** [genesluder/python-apns#4]
I there, I have got the issue below when using p8 file. I'm not sure how to fix it, hopefully we have a solution for it.

Thanks in advance

  File "/venv/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1084, in load_pem_private_key
    password,
  File "/venv/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1253, in _load_key
    self._handle_key_loading_error()
  File "/venv/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1325, in _handle_key_loading_error
    raise ValueError("Could not unserialize key data.")
ValueError: Could not unserialize key data.

My apns.p8 file has content as below
-----BEGIN PRIVATE KEY-----
MIGTAgeeca...................
-----END PRIVATE KEY-----

**Comment by hansg60** [comment]
I wonder if Apple has changed the format of their auth key files.

I'm having the same issue as datnguyen0606.  This weekend (Feb 4, 2017), I created a new auth token private key in my apple developer account  and the python-apns package is unable to unserialize the key.  I found a suggestion that the text in the key file should be wrapped to 64 characters per line, but doing that did not remove the exception.

**Comment by genesluder** [comment]
I haven't been able to reproduce this myself. I tried creating a new auth key as well. Other people have seen this issue per comments on a blog post I wrote, but since I've never been able to reproduce it, I've struggled to come up with a solution. 

One thing to note is that for some it seems to be OS dependent- for example the same code works on Mac OS but fails on a *nix distro. I'm wondering if this points to it being related to a library version (OpenSSL, cryptography, or PyJWT in particular)

I'm using this code on Mac OS and a few Debian 8 machines, with a mix of Python 2 & 3. 

A shot in the dark- but what versions of the above libs do you have installed? 

On my Mac:
PyJWT - 1.4.2
cryptography - 1.6
OpenSSL - 0.9.8zh

Debian:
PyJWT - 1.4.2
cryptography - 1.7
OpenSSL - 1.0.2j

**Comment by hansg60** [comment]
On my Ubuntu server, I had the following:
PyJWT - 1.4.2
cryptography - 1.2.2
OpenSSL - 1.0.1f

I upgraded PyJWT to 1.7, but still got the same exception.  Can you think of any other dependencies that could be wrong?

Here's the whole stacktrace:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/Allowance/AllowanceEnv/local/lib/python2.7/site-packages/gobiko/apns/client.py", line 63, in send_message
    return self._send_message(registration_id, alert, **kwargs)
  File "/home/ubuntu/Allowance/AllowanceEnv/local/lib/python2.7/site-packages/gobiko/apns/client.py", line 145, in _send_message
    auth_token = auth_token or self._create_token()
  File "/home/ubuntu/Allowance/AllowanceEnv/local/lib/python2.7/site-packages/gobiko/apns/client.py", line 90, in _create_token
    'kid': self.auth_key_id,
  File "/home/ubuntu/Allowance/AllowanceEnv/local/lib/python2.7/site-packages/jwt/api_jwt.py", line 56, in encode
    json_payload, key, algorithm, headers, json_encoder
  File "/home/ubuntu/Allowance/AllowanceEnv/local/lib/python2.7/site-packages/jwt/api_jws.py", line 98, in encode
    key = alg_obj.prepare_key(key)
  File "/home/ubuntu/Allowance/AllowanceEnv/local/lib/python2.7/site-packages/jwt/algorithms.py", line 226, in prepare_key
    key = load_pem_private_key(key, password=None, backend=default_backend())
  File "/home/ubuntu/Allowance/AllowanceEnv/local/lib/python2.7/site-packages/cryptography/hazmat/primitives/serialization.py", line 20, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/home/ubuntu/Allowance/AllowanceEnv/local/lib/python2.7/site-packages/cryptography/hazmat/backends/multibackend.py", line 305, in load_pem_private_key
    return b.load_pem_private_key(data, password)
  File "/home/ubuntu/Allowance/AllowanceEnv/local/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1084, in load_pem_private_key
    password,
  File "/home/ubuntu/Allowance/AllowanceEnv/local/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1253, in _load_key
    self._handle_key_loading_error()
  File "/home/ubuntu/Allowance/AllowanceEnv/local/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1325, in _handle_key_loading_error
    raise ValueError("Could not unserialize key data.")
ValueError: Could not unserialize key data.

Thanks,
Hans

**Comment by genesluder** [comment]
Someone had the same issue and opened a ticket here but never followed up: https://github.com/pyca/cryptography/issues/3232 

From that thread (slightly modified), you can try this to determine if the issue is with cryptography itself: 

    from cryptography.hazmat.backends.openssl.backend import backend 
    
    with open('APNsAuthKey_YOURKEY.p8') as f:
        key = f.read()

    backend.load_pem_private_key(key, None)

**Comment by hansg60** [comment]
When I do that, I get this exception:

  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/Allowance/AllowanceEnv/local/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1084, in load_pem_private_key
    password,
  File "/home/ubuntu/Allowance/AllowanceEnv/local/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1253, in _load_key
    self._handle_key_loading_error()
  File "/home/ubuntu/Allowance/AllowanceEnv/local/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1325, in _handle_key_loading_error
    raise ValueError("Could not unserialize key data.")
ValueError: Could not unserialize key data.

**Comment by hansg60** [comment]
Maybe this will help:

`python -V`
Python 2.7.13

`pip list`
appdirs (1.4.0)
attrs (16.3.0)
boto (2.45.0)
cffi (1.9.1)
chardet (2.3.0)
Cheetah (2.4.4)
cryptography (1.7.2)
Django (1.4.2)
django-email-as-username (1.6.4)
django-evolution (0.7.6)
enum34 (1.1.6)
h2 (2.5.2)
hpack (2.3.0)
hyper (0.7.0)
hyperframe (4.0.1)
idna (2.2)
ipaddress (1.0.18)
Markdown (2.6.8)
MySQL-python (1.2.5)
packaging (16.8)
pam (0.1.4)
pip (9.0.1)
pyasn1 (0.2.2)
pyasn1-modules (0.0.8)
pycparser (2.17)
pycrypto (2.6.1)
pycurl (7.43.0)
PyJWT (1.4.2)
pyOpenSSL (16.2.0)
pyparsing (2.1.10)
pyserial (3.2.1)
python-dateutil (2.6.0)
python-gcm (0.4)
pytz (2016.10)
PyYAML (3.12)
requests (2.13.0)
service-identity (16.0.0)
setuptools (34.1.1)
six (1.10.0)
urllib3 (1.20)

**Comment by hansg60** [comment]
I got a little further this morning. 
I created a new auth key on the apple developer site and tested opening it with the cryptography package, and got the same exception (as above).
Then I edited the new p8 file so that lines are max 64 characters per line, and I was able to open it with the cryptography package.  I got this:

```
backend.load_pem_private_key(key, None)
<cryptography.hazmat.backends.openssl.ec._EllipticCurvePrivateKey object at 0x7f3f8e5fe650>
```
When I limited the line length in the first auth key file, it made no difference -- I got the same exception.  

Then I tested your package with the following:
```
client = APNsClient(
    team_id=TEAM_ID,
    bundle_id=BUNDLE_ID,
    auth_key_id=APNS_KEY_ID,
    auth_key_filepath=APNS_KEY_FILEPATH,
    use_sandbox=False
)

client.send_message("03e602dac6039263213fb7d2dc5dde0625fbeeec1d1fa316a72d23c845ad074f", "All your base are belong to us.")
```

and got this exception:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/python2713/lib/python2.7/site-packages/gobiko/apns/client.py", line 63, in send_message
    return self._send_message(registration_id, alert, **kwargs)
  File "/home/ubuntu/python2713/lib/python2.7/site-packages/gobiko/apns/client.py", line 165, in _send_message
    response = self._send_push_request(connection, registration_id, json_data, request_headers)
  File "/home/ubuntu/python2713/lib/python2.7/site-packages/gobiko/apns/client.py", line 176, in _send_push_request
    response = connection.get_response()
  File "/home/ubuntu/python2713/lib/python2.7/site-packages/hyper/common/connection.py", line 129, in get_response
    return self._conn.get_response(*args, **kwargs)
  File "/home/ubuntu/python2713/lib/python2.7/site-packages/hyper/http11/connection.py", line 203, in get_response
    self._sock.fill()
  File "/home/ubuntu/python2713/lib/python2.7/site-packages/hyper/common/bufsocket.py", line 169, in fill
    raise ConnectionResetError()
hyper.common.exceptions.ConnectionResetError
```

I tried changing use_sandbox to True and False, but it didn't make a difference.
I tried adding force_proto='h2', but got the error: unexpected keyword argument 'force_proto'

Thanks

**Comment by hansg60** [comment]
I saw your post about this exception here: http://gobiko.com/blog/connection-reset-error-hyper-debian-jessie/

Is it necessary to use python 3.5?

**Comment by genesluder** [comment]
Python 2 is supported but there was an issue. I've updated the library on PyPI. Try upgrading the library and then add the force_proto argument: 

    client = APNsClient(
        team_id=TEAM_ID,
        bundle_id=BUNDLE_ID,
        auth_key_id=APNS_KEY_ID,
        auth_key_filepath=APNS_KEY_FILEPATH,
        use_sandbox=False,
        force_proto='h2'
    )

**Comment by genesluder** [comment]
I just saw that you already tried the **force_proto** argument. If you have the library installed via pip, the commit that added that argument wasn't in the most recent version. PyPI is now up to date and contains that fix.

**Comment by hansg60** [comment]
Hey, that worked, thanks!

Yesterday I was able to make your package work on a new install of Ubuntu 16.04 LTS, but I really didn't want to go through all the hassle of setting up the rest of the server right now.
Your package now works on my ubuntu 14.04 server with python 2.7.6 and without upgrading openssl.

Thank you,
Hans

**Comment by hansg60** [comment]
However, I do still need to limit the line length of the p8 file.  The original p8 file from Apple, still throws the "ValueError: Could not unserialize key data.".

**Comment by genesluder** [comment]
Glad the the second issue has been resolved! 

I just pushed a new commit that wraps the key to 64 lines in Python before generating the token. Since I haven't been able to reproduce the issue on any of my machines I can't verify that it fixes the problem- though theoretically it should and at least it doesn't do any harm. If you ever get a chance to test it let me know if it solves that for you!

**Comment by datnguyen0606** [comment]
Thanks @genesluder 
It seems to work now on python 2.7. The only thing we need to do is to update openSSL to newer version. I have updated it to version "OpenSSL 1.0.2k", and it works fine.

**Comment by genesluder** [comment]
Glad it's now working @datnguyen0606 And thanks for the tip on the OpenSSL version. 

I've added the changes to the newest version (0.1.3) on PyPI.

**Comment by fbartolom** [comment]
Apple itself provided me with this code also producing the error above:
```
import json
import jwt
import time

from hyper import HTTPConnection

ALGORITHM = 'ES256'

APNS_KEY_ID = 'ABCDEF'
APNS_AUTH_KEY = 'apns.p8'
TEAM_ID = 'GHIJK'
DEVICE_TOKEN = '975247bb6a1f7362ac34272888b9ae82b571d51ade36c5a18a7235a72de55079'
BUNDLE_ID = 'com.meditation.iPujaPro'
f = open(APNS_AUTH_KEY)
secret = f.read()
token = jwt.encode(
    {
        'iss': TEAM_ID,
        'iat': time.time()
    },
    secret,
    algorithm= ALGORITHM,
    headers={
        'alg': ALGORITHM,
        'kid': APNS_KEY_ID
    }
)
path = '/3/device/{0}'.format(DEVICE_TOKEN)

request_headers = {
    'apns-expiration': '0',
    'apns-priority': '10',
    'apns-topic': BUNDLE_ID,
    'authorization': 'bearer {0}'.format(token.decode('ascii'))
}

# Open a connection the APNS server
conn = HTTPConnection('api.development.push.apple.com:443')

payload_data = {
    "aps" : { "alert" : "Message received from Bob" },"acme2" : [ "bang",  "whiz" ]
}
payload = json.dumps(payload_data).encode('utf-8')

# Send our request
conn.request(
    'POST',
    path,
    payload,
    headers=request_headers
)
resp = conn.get_response()
print(resp.status)
print(resp.read())
```
So it should not be a problem with Apple. This is the error I get with python 3.5:

> Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/jwt/algorithms.py", line 224, in prepare_key
    key = load_pem_public_key(key, backend=default_backend())
  File "/usr/local/lib/python3.5/site-packages/cryptography/hazmat/primitives/serialization.py", line 24, in load_pem_public_key
    return backend.load_pem_public_key(data)
  File "/usr/local/lib/python3.5/site-packages/cryptography/hazmat/backends/multibackend.py", line 314, in load_pem_public_key
    return b.load_pem_public_key(data)
  File "/usr/local/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1110, in load_pem_public_key
    self._handle_key_loading_error()
  File "/usr/local/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1325, in _handle_key_loading_error
    raise ValueError("Could not unserialize key data.")
ValueError: Could not unserialize key data.

> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "simpleNotification.py", line 25, in <module>
>     'kid': APNS_KEY_ID
>   File "/usr/local/lib/python3.5/site-packages/jwt/api_jwt.py", line 56, in encode
>     json_payload, key, algorithm, headers, json_encoder
>   File "/usr/local/lib/python3.5/site-packages/jwt/api_jws.py", line 98, in encode
>     key = alg_obj.prepare_key(key)
>   File "/usr/local/lib/python3.5/site-packages/jwt/algorithms.py", line 226, in prepare_key
>     key = load_pem_private_key(key, password=None, backend=default_backend())
>   File "/usr/local/lib/python3.5/site-packages/cryptography/hazmat/primitives/serialization.py", line 20, in load_pem_private_key
>     return backend.load_pem_private_key(data, password)
>   File "/usr/local/lib/python3.5/site-packages/cryptography/hazmat/backends/multibackend.py", line 305, in load_pem_private_key
>     return b.load_pem_private_key(data, password)
>   File "/usr/local/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1084, in load_pem_private_key
>     password,
>   File "/usr/local/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1253, in _load_key
>     self._handle_key_loading_error()
>   File "/usr/local/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1325, in _handle_key_loading_error
>     raise ValueError("Could not unserialize key data.")
> ValueError: Could not unserialize key data.
